### ISSUE TITLE
[2022.02.07~ 2022.02.14] 게시글 관련 작업 To-do

### ISSUE THREAD

**Issue by tlsdhsdb** [Every-Time-Clone/every-time#3]
- [x] 게시글 생성 성공,실패 로직 작성하기
- [x] update dto 형식에 맞게 새로 구성하기
- [x] 게시글 삭제 로직 구현하기
